this is the file that prepare the german_data since the string type is not so suitable for the model, and sine we want only the sex part, we want to see others as simple as possible.

there are totally 7 numerical, 13 categorical variables, this prepare work on the German_data, which have been treated on the sex and good/bad

In [17]:
import pandas as pd

In [18]:
German_data = pd.read_csv("/Users/liuxinhao/Desktop/fair german data/data/German_data.csv")

In [19]:
German_data.head()
German_data.drop("Personal_status_and_sex",axis = 1, inplace = True)

In [20]:
German_data

,Status_of_existing_checking_account,Duration_in_month,Credit_history,Purpose,Credit_amount,Savings_account/bonds,Present_employment_since,Installment_rate_in_percentage_of_disposable_income,Other_debtors/guarantors,Present_residence_since,...,Age_in_years,Other_installment_plans,Housing,Number_of_existing_credits_at_this_bank,Job,Number_of_people_being_liable_to_provide_maintenance_for,Telephone,Foreign_worker,Good/Bad,sex
0,A12,48,A32,A43,5951,A61,A73,2,A101,2,...,22,A143,A152,1,A173,1,A191,A201,0,0
1,A14,12,A34,A46,2096,A61,A74,2,A101,3,...,49,A143,A152,1,A172,2,A191,A201,1,1
2,A11,42,A32,A42,7882,A61,A74,2,A103,4,...,45,A143,A153,1,A173,2,A191,A201,1,1
3,A11,24,A33,A40,4870,A61,A73,3,A101,4,...,53,A143,A153,2,A173,2,A191,A201,0,1
4,A14,36,A32,A46,9055,A65,A73,2,A101,4,...,35,A143,A153,1,A172,2,A192,A201,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,A14,12,A32,A42,1736,A61,A74,3,A101,4,...,31,A143,A152,1,A172,1,A191,A201,1,0
995,A11,30,A32,A41,3857,A61,A73,4,A101,4,...,40,A143,A152,1,A174,1,A192,A201,1,1
996,A14,12,A32,A43,804,A61,A75,4,A101,4,...,38,A143,A152,1,A173,1,A191,A201,1,1
997,A11,45,A32,A43,1845,A61,A73,4,A101,4,...,23,A143,A153,1,A173,1,A192,A201,0,1
998,A12,45,A34,A41,4576,A62,A71,3,A101,4,...,27,A143,A152,1,A173,1,A191,A201,1,1

处理：尝试对所有的category变量进行独热编码
有可能出现数据维度过高的情况

In [22]:
from sklearn.preprocessing import OneHotEncoder
# 创建OneHotEncoder对象
encoder = OneHotEncoder()
category = ['Status_of_existing_checking_account','Credit_history','Purpose','Savings_account/bonds','Present_employment_since','Other_debtors/guarantors','Property','Other_installment_plans','Housing','Job','Telephone','Foreign_worker']
# 将属性17进行独热编码
encoded_German_data = encoder.fit_transform(German_data[category])

# 将稀疏矩阵转换为密集矩阵
dense_encoded_German_data = encoded_German_data.toarray()

# 将密集矩阵转换为DataFrame
df_encoded_German_data = pd.DataFrame(dense_encoded_German_data, columns=encoder.get_feature_names_out(category))

# 打印DataFrame
print(df_encoded_German_data)

# # 使用标签编码（Label Encoding）
# from sklearn.preprocessing import LabelEncoder

# # 创建LabelEncoder对象
# encoder = LabelEncoder()

# # 将属性17进行标签编码
# encoded_German_data = encoder.fit_transform(German_data[category])

# # 打印标签编码后的特征
# print(encoded_German_data)

     Status_of_existing_checking_account_A11  \
0                                        0.0
1                                        0.0
2                                        1.0
3                                        1.0
4                                        0.0
..                                       ...
994                                      0.0
995                                      1.0
996                                      0.0
997                                      1.0
998                                      0.0

     Status_of_existing_checking_account_A12  \
0                                        1.0
1                                        0.0
2                                        0.0
3                                        0.0
4                                        0.0
..                                       ...
994                                      0.0
995                                      0.0
996                                      0.0
997                                      0.0
998                                      1.0

     Status_of_existing_checking_account_A13  \
0                                        0.0
1                                        0.0
2                                        0.0
3                                        0.0
4                                        0.0
..                                       ...
994                                      0.0
995                                      0.0
996                                      0.0
997                                      0.0
998                                      0.0

     Status_of_existing_checking_account_A14  Credit_history_A30  \
0                                        0.0                 0.0
1                                        1.0                 0.0
2                                        0.0                 0.0
3                                        0.0                 0.0
4                                        1.0                 0.0
..                                       ...                 ...
994                                      1.0                 0.0
995                                      0.0                 0.0
996                                      1.0                 0.0
997                                      0.0                 0.0
998                                      0.0                 0.0

     Credit_history_A31  Credit_history_A32  Credit_history_A33  \
0                   0.0                 1.0                 0.0
1                   0.0                 0.0                 0.0
2                   0.0                 1.0                 0.0
3                   0.0                 0.0                 1.0
4                   0.0                 1.0                 0.0
..                  ...                 ...                 ...
994                 0.0                 1.0                 0.0
995                 0.0                 1.0                 0.0
996                 0.0                 1.0                 0.0
997                 0.0                 1.0                 0.0
998                 0.0                 0.0                 0.0

     Credit_history_A34  Purpose_A40  ...  Housing_A152  Housing_A153  \
0                   0.0          0.0  ...           1.0           0.0
1                   1.0          0.0  ...           1.0           0.0
2                   0.0          0.0  ...           0.0           1.0
3                   0.0          1.0  ...           0.0           1.0
4                   0.0          0.0  ...           0.0           1.0
..                  ...          ...  ...           ...           ...
994                 0.0          0.0  ...           1.0           0.0
995                 0.0          0.0  ...           1.0           0.0
996                 0.0          0.0  ...           1.0           0.0
997                 0.0          0.0  ...           0.0           1.0
998                 1.0          0.0  ...           1.0           0.0

     Job_A171  Job_A172  Job_A173  Job_A174  Telephone_A191  Telephone_A192  \
0         0.0       0.0       1.0       0.0             1.0             0.0
1         0.0       1.0       0.0       0.0             1.0             0.0
2         0.0       0.0       1.0       0.0             1.0             0.0
3         0.0       0.0       1.0       0.0             1.0             0.0
4         0.0       1.0       0.0       0.0             0.0             1.0
..        ...       ...       ...       ...             ...             ...
994       0.0       1.0       0.0       0.0             1.0             0.0
995       0.0       0.0       0.0       1.0             0.0             1.0
996       0.0       0.0       1.0       0.0             1.0             0.0
997       0.0       0.0       1.0       0.0             0.0             1.0
998       0.0       0.0       1.0       0.0             1.0             0.0

     Foreign_worker_A201  Foreign_worker_A202
0                    1.0                  0.0
1                    1.0                  0.0
2                    1.0                  0.0
3                    1.0                  0.0
4                    1.0                  0.0
..                   ...                  ...
994                  1.0                  0.0
995                  1.0                  0.0
996                  1.0                  0.0
997                  1.0                  0.0
998                  1.0                  0.0

[999 rows x 50 columns]

In [24]:
German_data.columns
German_data.drop("Telephone",axis = 1, inplace = True) # here this telephone do not have effect on our model
numerical_var = ['Duration_in_month','Credit_amount','Present_residence_since','Age_in_years','Number_of_existing_credits_at_this_bank','Number_of_people_being_liable_to_provide_maintenance_for','Good/Bad', 'sex']
numerical = German_data[numerical_var]

In [30]:
result = pd.concat([df_encoded_German_data, numerical],axis = 1)
print(result)

     Status_of_existing_checking_account_A11  \
0                                        0.0
1                                        0.0
2                                        1.0
3                                        1.0
4                                        0.0
..                                       ...
994                                      0.0
995                                      1.0
996                                      0.0
997                                      1.0
998                                      0.0

     Status_of_existing_checking_account_A12  \
0                                        1.0
1                                        0.0
2                                        0.0
3                                        0.0
4                                        0.0
..                                       ...
994                                      0.0
995                                      0.0
996                                      0.0
997                                      0.0
998                                      1.0

     Status_of_existing_checking_account_A13  \
0                                        0.0
1                                        0.0
2                                        0.0
3                                        0.0
4                                        0.0
..                                       ...
994                                      0.0
995                                      0.0
996                                      0.0
997                                      0.0
998                                      0.0

     Status_of_existing_checking_account_A14  Credit_history_A30  \
0                                        0.0                 0.0
1                                        1.0                 0.0
2                                        0.0                 0.0
3                                        0.0                 0.0
4                                        1.0                 0.0
..                                       ...                 ...
994                                      1.0                 0.0
995                                      0.0                 0.0
996                                      1.0                 0.0
997                                      0.0                 0.0
998                                      0.0                 0.0

     Credit_history_A31  Credit_history_A32  Credit_history_A33  \
0                   0.0                 1.0                 0.0
1                   0.0                 0.0                 0.0
2                   0.0                 1.0                 0.0
3                   0.0                 0.0                 1.0
4                   0.0                 1.0                 0.0
..                  ...                 ...                 ...
994                 0.0                 1.0                 0.0
995                 0.0                 1.0                 0.0
996                 0.0                 1.0                 0.0
997                 0.0                 1.0                 0.0
998                 0.0                 0.0                 0.0

     Credit_history_A34  Purpose_A40  ...  Foreign_worker_A201  \
0                   0.0          0.0  ...                  1.0
1                   1.0          0.0  ...                  1.0
2                   0.0          0.0  ...                  1.0
3                   0.0          1.0  ...                  1.0
4                   0.0          0.0  ...                  1.0
..                  ...          ...  ...                  ...
994                 0.0          0.0  ...                  1.0
995                 0.0          0.0  ...                  1.0
996                 0.0          0.0  ...                  1.0
997                 0.0          0.0  ...                  1.0
998                 1.0          0.0  ...                  1.0

     Foreign_worker_A202  Duration_in_month  Credit_amount  \
0                    0.0                 48           5951
1                    0.0                 12           2096
2                    0.0                 42           7882
3                    0.0                 24           4870
4                    0.0                 36           9055
..                   ...                ...            ...
994                  0.0                 12           1736
995                  0.0                 30           3857
996                  0.0                 12            804
997                  0.0                 45           1845
998                  0.0                 45           4576

     Present_residence_since  Age_in_years  \
0                          2            22
1                          3            49
2                          4            45
3                          4            53
4                          4            35
..                       ...           ...
994                        4            31
995                        4            40
996                        4            38
997                        4            23
998                        4            27

     Number_of_existing_credits_at_this_bank  \
0                                          1
1                                          1
2                                          1
3                                          2
4                                          1
..                                       ...
994                                        1
995                                        1
996                                        1
997                                        1
998                                        1

     Number_of_people_being_liable_to_provide_maintenance_for  Good/Bad  sex
0                                                    1                0    0
1                                                    2                1    1
2                                                    2                1    1
3                                                    2                0    1
4                                                    2                1    1
..                                                 ...              ...  ...
994                                                  1                1    0
995                                                  1                1    1
996                                                  1                1    1
997                                                  1                0    1
998                                                  1                1    1

[999 rows x 58 columns]

In [31]:
result.isna().sum()

Status_of_existing_checking_account_A11                     0
Status_of_existing_checking_account_A12                     0
Status_of_existing_checking_account_A13                     0
Status_of_existing_checking_account_A14                     0
Credit_history_A30                                          0
Credit_history_A31                                          0
Credit_history_A32                                          0
Credit_history_A33                                          0
Credit_history_A34                                          0
Purpose_A40                                                 0
Purpose_A41                                                 0
Purpose_A410                                                0
Purpose_A42                                                 0
Purpose_A43                                                 0
Purpose_A44                                                 0
Purpose_A45                                                 0
Purpose_A46                                                 0
Purpose_A48                                                 0
Purpose_A49                                                 0
Savings_account/bonds_A61                                   0
Savings_account/bonds_A62                                   0
Savings_account/bonds_A63                                   0
Savings_account/bonds_A64                                   0
Savings_account/bonds_A65                                   0
Present_employment_since_A71                                0
Present_employment_since_A72                                0
Present_employment_since_A73                                0
Present_employment_since_A74                                0
Present_employment_since_A75                                0
Other_debtors/guarantors_A101                               0
Other_debtors/guarantors_A102                               0
Other_debtors/guarantors_A103                               0
Property_A121                                               0
Property_A122                                               0
Property_A123                                               0
Property_A124                                               0
Other_installment_plans_A141                                0
Other_installment_plans_A142                                0
Other_installment_plans_A143                                0
Housing_A151                                                0
Housing_A152                                                0
Housing_A153                                                0
Job_A171                                                    0
Job_A172                                                    0
Job_A173                                                    0
Job_A174                                                    0
Telephone_A191                                              0
Telephone_A192                                              0
Foreign_worker_A201                                         0
Foreign_worker_A202                                         0
Duration_in_month                                           0
Credit_amount                                               0
Present_residence_since                                     0
Age_in_years                                                0
Number_of_existing_credits_at_this_bank                     0
Number_of_people_being_liable_to_provide_maintenance_for    0
Good/Bad                                                    0
sex                                                         0
dtype: int64

In [32]:
result.to_csv('/Users/liuxinhao/Desktop/fair german data/data/German_data.csv', index=False)

In [34]:
result.columns

Index(['Status_of_existing_checking_account_A11',
       'Status_of_existing_checking_account_A12',
       'Status_of_existing_checking_account_A13',
       'Status_of_existing_checking_account_A14', 'Credit_history_A30',
       'Credit_history_A31', 'Credit_history_A32', 'Credit_history_A33',
       'Credit_history_A34', 'Purpose_A40', 'Purpose_A41', 'Purpose_A410',
       'Purpose_A42', 'Purpose_A43', 'Purpose_A44', 'Purpose_A45',
       'Purpose_A46', 'Purpose_A48', 'Purpose_A49',
       'Savings_account/bonds_A61', 'Savings_account/bonds_A62',
       'Savings_account/bonds_A63', 'Savings_account/bonds_A64',
       'Savings_account/bonds_A65', 'Present_employment_since_A71',
       'Present_employment_since_A72', 'Present_employment_since_A73',
       'Present_employment_since_A74', 'Present_employment_since_A75',
       'Other_debtors/guarantors_A101', 'Other_debtors/guarantors_A102',
       'Other_debtors/guarantors_A103', 'Property_A121', 'Property_A122',
       'Property_A123', 'Property_A124', 'Other_installment_plans_A141',
       'Other_installment_plans_A142', 'Other_installment_plans_A143',
       'Housing_A151', 'Housing_A152', 'Housing_A153', 'Job_A171', 'Job_A172',
       'Job_A173', 'Job_A174', 'Telephone_A191', 'Telephone_A192',
       'Foreign_worker_A201', 'Foreign_worker_A202', 'Duration_in_month',
       'Credit_amount', 'Present_residence_since', 'Age_in_years',
       'Number_of_existing_credits_at_this_bank',
       'Number_of_people_being_liable_to_provide_maintenance_for', 'Good/Bad',
       'sex'],
      dtype='object')